version: 2.1

jobs:
  build_macos:
    macos:
      xcode: "12.5.1"
    steps:
      - run:
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            make

workflows:
  test_build:
    jobs:
      - build_macos
