version: 2.1

jobs:
  build_macos:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          command: |
            make
            ./lldb.sh

workflows:
  build_macos:
    jobs:
      - build_macos
          filters:
            branches:
              only:
                - master
                - development
